from __future__ import annotations

APP_NAME = "Video Unicalizator"
APP_VERSION = "0.2.0"

TARGET_WIDTH = 1080
TARGET_HEIGHT = 1920
TARGET_ASPECT_RATIO = TARGET_WIDTH / TARGET_HEIGHT
DEFAULT_FPS = 30

MAX_ORIGINALS = 5
MIN_VARIATIONS = 10
MAX_VARIATIONS = 20
DEFAULT_VARIATIONS = 10

MUSIC_VOLUME = 0.10
SPEED_MIN = 0.90
SPEED_MAX = 1.20

DEFAULT_TEXT_COLOR = "#FFFFFF"
DEFAULT_BG_COLOR = "#101010"
DEFAULT_BG_OPACITY = 0.45
DEFAULT_SHADOW_STRENGTH = 0.45
DEFAULT_FONT_SIZE = 64
DEFAULT_PREVIEW_TEXT = "Ваша цитата"
DEFAULT_BOX_WIDTH_RATIO = 0.72
DEFAULT_LINE_SPACING = 1.18
DEFAULT_PADDING_X_RATIO = 0.55
DEFAULT_PADDING_Y_RATIO = 0.35
DEFAULT_CORNER_RADIUS = 36
DEFAULT_TEXT_ALIGN = "center"

DEFAULT_OUTPUT_CODEC = "libx264"
DEFAULT_AUDIO_CODEC = "aac"
DEFAULT_CRF = 18
DEFAULT_PRESET = "veryfast"

MIN_SHARPNESS_SCORE = 80.0
MIN_VISUAL_DIFFERENCE = 6.0

SCHEDULE_INTERVAL_MIN_HOURS = 1.5
SCHEDULE_INTERVAL_MAX_HOURS = 3.0

PREVIEW_MIN_ZOOM = 1.0
PREVIEW_MAX_ZOOM = 4.0
PREVIEW_ZOOM_STEP = 1.15

SUPPORTED_VIDEO_EXTENSIONS = {".mp4"}
SUPPORTED_AUDIO_EXTENSIONS = {".mp3"}
SUPPORTED_TEXT_EXTENSIONS = {".txt"}
